### ISSUE TITLE
odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ odio c++ 

### ISSUE THREAD

**Issue by asdru22** [bugboy-20/Debugging-of-Isaac#17]
le voci mi dicono che i linguaggi di programmazione basati troppo sui puntatori a memoria fanno schifo le voci le voci le voci le voci le voci le voci le voci le voci le voci le voci le voci le voci le voci le voci

**Comment by bugboy-20** [comment]
Su su è tutto finito
