### ISSUE TITLE
bits/types/time_t.h non funziona

### ISSUE THREAD

**Issue by jantizio** [bugboy-20/Debugging-of-Isaac#4]
#include <bits/types/time_t.h> da un errore. 
Queste librerie sono preinstallate su windows? oppure vanno scaricate a parte.
Quale dovrebbe essere l'include giusto per windows?

Bisogna fare delle ricerche

**Comment by bugboy-20** [comment]
time_t sicuramente esiste anche su windows, prova a cambiare in locale `#include <bits/types/time_t.h>` in `#include<time.h>`

**Comment by jantizio** [comment]
ok con time.h funziona tutto tranne la funzione `usleep()`

**Comment by jantizio** [comment]
La soluzione che ho trovato è stata questa:
https://stackoverflow.com/questions/5801813/c-usleep-is-obsolete-workarounds-for-windows-mingw

In pratica si tratta di aggiungere manualmente l'implementazione di `usleeep()`

**Comment by bugboy-20** [comment]
Piske pirata
